project_id = "bgnvfsjdcpphczaaovwx"

[functions.chat]
verify_jwt = false

[functions.role-play-chat]
verify_jwt = false

[functions.super-agent-chat]
verify_jwt = false

[functions.reflection-questions]
verify_jwt = false
