// Hand-authored skeleton for Associate Investment Manager catalog.
// Prose fields (summaries, criteria, scenarios, etc.) are expanded by Lovable AI
// in the catalog-import edge function. Codes, structure, types, tags, and
// pedagogical mix are fixed here.

export type ChapterSkeleton = {
  chapter_code: string;
  chapter_title: string;
  learning_objective: string;
  content_type:
    | "reading" | "video" | "podcast" | "interactive_simulation"
    | "scenario_walkthrough" | "case_study" | "live_workshop"
    | "shadowing" | "mentor_discussion" | "observed_practice"
    | "workplace_assignment" | "system_practice" | "coaching" | "self_study";
  estimated_time_minutes: number;
  difficulty_level: "foundation" | "practitioner" | "advanced" | "leadership";
  delivery_mode:
    | "digital" | "offline" | "blended" | "live_cohort"
    | "simulation" | "workplace_practice" | "coaching";
  topic_tags: string[];
  related_capabilities: string[];
  complexity: number; // 1.0 – 3.0
};

export type BlueprintSkeleton = {
  blueprint_code: string;
  scope: "milestone" | "module_post";
  chapter_code?: string;
  assessment_type:
    | "knowledge_check_mcq" | "scenario_response" | "written_short_answer"
    | "written_long_form" | "case_analysis" | "client_simulation_voice"
    | "client_simulation_chat" | "role_play_assessed" | "system_task_simulation"
    | "calculation_exercise" | "portfolio_construction_task" | "compliance_review_task"
    | "peer_review" | "manager_observation" | "mentor_signoff"
    | "external_certification" | "reflective_journal" | "presentation_assessed"
    | "evidence_portfolio";
  assessment_title: string;
  passing_score?: number;
  scoring_dimensions: { label: string; weight: number; descriptor: string }[];
  topic_outline: { topic: string; sub_points: string[] }[];
  evidence_generated: string[];
};

export type EvidenceSkeleton = {
  evidence_task_code: string;
  evidence_title: string;
  evidence_type:
    | "client_meeting_note" | "portfolio_proposal" | "trade_rationale"
    | "compliance_log" | "shadowing_log" | "mentor_feedback_form"
    | "manager_observation_form" | "reflective_writeup" | "system_screenshot_pack"
    | "presentation_deck" | "peer_feedback" | "case_writeup";
  reviewer_role: "manager" | "mentor" | "assessor" | "peer" | "self";
  submission_format: "written" | "upload" | "observation" | "system_record" | "recording";
  required_for_gate: boolean;
};

export type ModuleSkeleton = {
  module_code: string;
  module_title: string;
  domain_code: string;
  role_cohort_code: string;
  learning_track_code: string;
  progression_stage: string;
  target_capabilities: string[];
  estimated_effort_hours: number;
  difficulty_level: "foundation" | "practitioner" | "advanced" | "leadership";
  prerequisite_module_codes: string[];
  is_core_required: boolean;
  is_stretch_module: boolean;
  stretch_target_role_cohort: string | null;
  recommended_delivery_mode:
    | "digital" | "offline" | "blended" | "live_cohort"
    | "simulation" | "workplace_practice" | "coaching";
  nudge_trigger_tags: string[];
  stretch_unlock_conditions: string[];
  risk_flags_if_not_completed: string[];
  display_order: number;
  chapters: ChapterSkeleton[];
  blueprints: BlueprintSkeleton[];
  evidence_tasks: EvidenceSkeleton[];
  /** Gate codes this module satisfies. */
  contributes_to_gates: string[];
};

const DOMAIN = "investment_management";
const ROLE = "assoc_im";
const STAGE = "associate_investment_manager_18m";
const GATE = "gate.im_readiness";

// ───────────────────────── Business Knowledge (5) ─────────────────────────
const businessKnowledge: ModuleSkeleton[] = [
  {
    module_code: "bk1.intro_wealth_rathbones",
    module_title: "Introduction to Wealth Management and the Rathbones Approach",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "business_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["wealth_management_landscape", "rathbones_house_view", "client_proposition_understanding"],
    estimated_effort_hours: 4, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["onboarding_week_1", "house_view_briefing"],
    stretch_unlock_conditions: [], risk_flags_if_not_completed: ["client_handover_unsafe"],
    display_order: 10,
    chapters: [
      { chapter_code: "bk1.c1", chapter_title: "What is Discretionary Wealth Management?",
        learning_objective: "Distinguish discretionary, advisory and execution-only models and place Rathbones within the UK wealth landscape.",
        content_type: "reading", estimated_time_minutes: 25, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["wealth_models", "uk_market"],
        related_capabilities: ["wealth_management_landscape"], complexity: 1.2 },
      { chapter_code: "bk1.c2", chapter_title: "The Rathbones House View and Investment Philosophy",
        learning_objective: "Explain the firm's investment beliefs, asset allocation framework and how the house view reaches client portfolios.",
        content_type: "video", estimated_time_minutes: 30, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["house_view", "investment_philosophy"],
        related_capabilities: ["rathbones_house_view"], complexity: 1.5 },
      { chapter_code: "bk1.c3", chapter_title: "Shadowing a Senior IM Client Review",
        learning_objective: "Observe how a Senior Investment Manager translates the house view into a live client conversation.",
        content_type: "shadowing", estimated_time_minutes: 60, difficulty_level: "foundation",
        delivery_mode: "workplace_practice", topic_tags: ["client_review", "house_view_in_practice"],
        related_capabilities: ["client_proposition_understanding"], complexity: 1.8 },
    ],
    blueprints: [
      { blueprint_code: "bk1.bp_post", scope: "module_post", assessment_type: "scenario_response",
        assessment_title: "Positioning the Rathbones Proposition",
        scoring_dimensions: [
          { label: "Accuracy of model distinctions", weight: 30, descriptor: "Correctly contrasts discretionary vs advisory" },
          { label: "Use of house view language", weight: 30, descriptor: "Applies the firm's framing without jargon errors" },
          { label: "Client-appropriate tone", weight: 20, descriptor: "Adjusts language for a non-expert client" },
          { label: "Compliance awareness", weight: 20, descriptor: "Avoids advice-style statements outside remit" },
        ],
        topic_outline: [
          { topic: "Discretionary vs advisory", sub_points: ["Decision authority", "Suitability obligations"] },
          { topic: "House view application", sub_points: ["Asset allocation overlay", "Tactical positioning"] },
        ],
        evidence_generated: ["client_explanation_writeup"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "bk1.ev_shadowing", evidence_title: "Shadowing Reflection — Senior IM Review",
        evidence_type: "shadowing_log", reviewer_role: "manager", submission_format: "written",
        required_for_gate: true },
    ],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "bk2.kyc_suitability",
    module_title: "Client Segmentation, KYC and Suitability Foundations",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "business_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["kyc_execution", "suitability_assessment", "client_segmentation"],
    estimated_effort_hours: 6, difficulty_level: "foundation",
    prerequisite_module_codes: ["bk1.intro_wealth_rathbones"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["pre_first_kyc_meeting", "suitability_letter_drafting"],
    stretch_unlock_conditions: [], risk_flags_if_not_completed: ["unsuitable_advice_risk", "fca_breach_risk"],
    display_order: 20,
    chapters: [
      { chapter_code: "bk2.c1", chapter_title: "KYC, ATR and Capacity for Loss",
        learning_objective: "Capture and interpret KYC, attitude to risk and capacity for loss to evidence suitability.",
        content_type: "case_study", estimated_time_minutes: 35, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["kyc", "atr", "capacity_for_loss"],
        related_capabilities: ["kyc_execution"], complexity: 1.8 },
      { chapter_code: "bk2.c2", chapter_title: "Client Segmentation at Rathbones",
        learning_objective: "Segment clients by needs, complexity and value, and select the right service model.",
        content_type: "reading", estimated_time_minutes: 25, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["segmentation", "service_levels"],
        related_capabilities: ["client_segmentation"], complexity: 1.5 },
      { chapter_code: "bk2.c3", chapter_title: "Drafting a Suitability Statement",
        learning_objective: "Produce a compliant suitability statement linking client facts to portfolio recommendation.",
        content_type: "workplace_assignment", estimated_time_minutes: 60, difficulty_level: "practitioner",
        delivery_mode: "workplace_practice", topic_tags: ["suitability_letter"],
        related_capabilities: ["suitability_assessment"], complexity: 2.4 },
    ],
    blueprints: [
      { blueprint_code: "bk2.bp_mid", scope: "milestone", chapter_code: "bk2.c1",
        assessment_type: "knowledge_check_mcq",
        assessment_title: "KYC Foundations Progress Check",
        scoring_dimensions: [
          { label: "Definitions accuracy", weight: 50, descriptor: "Correctly defines KYC, ATR, CFL" },
          { label: "Application", weight: 50, descriptor: "Applies definitions to short scenarios" },
        ],
        topic_outline: [
          { topic: "KYC data points", sub_points: ["Personal", "Financial", "Objectives"] },
          { topic: "ATR vs CFL", sub_points: ["Conceptual differences", "Evidence sources"] },
        ],
        evidence_generated: [] },
      { blueprint_code: "bk2.bp_post", scope: "module_post", assessment_type: "case_analysis",
        assessment_title: "Suitability Case — Recommend and Justify",
        scoring_dimensions: [
          { label: "Fact gathering completeness", weight: 25, descriptor: "Identifies missing KYC data" },
          { label: "Risk profiling logic", weight: 25, descriptor: "Justifies ATR and CFL conclusions" },
          { label: "Recommendation fit", weight: 30, descriptor: "Recommendation aligns with profile" },
          { label: "Compliance phrasing", weight: 20, descriptor: "Uses defensible suitability wording" },
        ],
        topic_outline: [
          { topic: "Client facts triangulation", sub_points: ["Cross-checks", "Gap identification"] },
          { topic: "Recommendation justification", sub_points: ["Linking facts to mandate"] },
        ],
        evidence_generated: ["draft_suitability_statement"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "bk2.ev_suitability_letter",
        evidence_title: "Draft Suitability Statement on a Synthetic Client",
        evidence_type: "case_writeup", reviewer_role: "assessor", submission_format: "upload",
        required_for_gate: true },
    ],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "bk3.markets_macro_assets",
    module_title: "Markets, Macro and Asset Class Fundamentals",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "business_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["macro_literacy", "asset_class_fundamentals", "market_commentary_authoring"],
    estimated_effort_hours: 8, difficulty_level: "practitioner",
    prerequisite_module_codes: ["bk1.intro_wealth_rathbones"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["weekly_market_update", "client_macro_question"],
    stretch_unlock_conditions: [], risk_flags_if_not_completed: ["client_credibility_gap"],
    display_order: 30,
    chapters: [
      { chapter_code: "bk3.c1", chapter_title: "Macro Drivers — Rates, Inflation, Growth",
        learning_objective: "Explain how core macro variables transmit to asset prices.",
        content_type: "reading", estimated_time_minutes: 35, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["macro", "rates", "inflation"],
        related_capabilities: ["macro_literacy"], complexity: 2.2 },
      { chapter_code: "bk3.c2", chapter_title: "Equities, Fixed Income, Alternatives — Roles in a Portfolio",
        learning_objective: "Map asset class characteristics to client objectives and risk profiles.",
        content_type: "video", estimated_time_minutes: 30, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["equities", "fixed_income", "alternatives"],
        related_capabilities: ["asset_class_fundamentals"], complexity: 2.0 },
      { chapter_code: "bk3.c3", chapter_title: "Writing a Weekly Market Note",
        learning_objective: "Produce a 250-word client-facing market commentary in Rathbones tone.",
        content_type: "workplace_assignment", estimated_time_minutes: 45, difficulty_level: "practitioner",
        delivery_mode: "workplace_practice", topic_tags: ["market_commentary"],
        related_capabilities: ["market_commentary_authoring"], complexity: 2.4 },
    ],
    blueprints: [
      { blueprint_code: "bk3.bp_post", scope: "module_post", assessment_type: "written_long_form",
        assessment_title: "Macro-to-Portfolio Briefing Note",
        scoring_dimensions: [
          { label: "Macro accuracy", weight: 30, descriptor: "Cites correct mechanisms" },
          { label: "Asset class linkage", weight: 30, descriptor: "Links macro to allocation moves" },
          { label: "Clarity and tone", weight: 25, descriptor: "Client-readable, Rathbones tone" },
          { label: "Balanced framing", weight: 15, descriptor: "Presents risks alongside views" },
        ],
        topic_outline: [
          { topic: "Macro snapshot", sub_points: ["Rates path", "Inflation regime"] },
          { topic: "Implications", sub_points: ["Equity tilt", "Duration stance"] },
        ],
        evidence_generated: ["market_briefing_note"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "bk3.ev_market_note",
        evidence_title: "Published Market Note Reviewed by Mentor",
        evidence_type: "case_writeup", reviewer_role: "mentor", submission_format: "upload",
        required_for_gate: false },
    ],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "bk4.portfolio_construction",
    module_title: "Portfolio Construction Principles for Associate IMs",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "business_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["portfolio_construction", "model_portfolio_application", "rebalancing_logic"],
    estimated_effort_hours: 7, difficulty_level: "practitioner",
    prerequisite_module_codes: ["bk3.markets_macro_assets"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["pre_rebalance", "model_portfolio_drift_alert"],
    stretch_unlock_conditions: [], risk_flags_if_not_completed: ["mandate_drift_risk"],
    display_order: 40,
    chapters: [
      { chapter_code: "bk4.c1", chapter_title: "Strategic vs Tactical Asset Allocation",
        learning_objective: "Differentiate SAA and TAA and describe Rathbones' framework.",
        content_type: "reading", estimated_time_minutes: 30, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["saa", "taa"],
        related_capabilities: ["portfolio_construction"], complexity: 2.0 },
      { chapter_code: "bk4.c2", chapter_title: "Applying Model Portfolios to Live Clients",
        learning_objective: "Translate a model portfolio to a real client mandate, accounting for legacy holdings and tax.",
        content_type: "scenario_walkthrough", estimated_time_minutes: 45, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["model_portfolios", "legacy_holdings"],
        related_capabilities: ["model_portfolio_application"], complexity: 2.5 },
      { chapter_code: "bk4.c3", chapter_title: "Rebalancing and Drift Monitoring",
        learning_objective: "Identify drift breaches and propose rebalancing trades within mandate constraints.",
        content_type: "system_practice", estimated_time_minutes: 50, difficulty_level: "practitioner",
        delivery_mode: "simulation", topic_tags: ["rebalancing", "drift"],
        related_capabilities: ["rebalancing_logic"], complexity: 2.6 },
    ],
    blueprints: [
      { blueprint_code: "bk4.bp_post", scope: "module_post",
        assessment_type: "portfolio_construction_task",
        assessment_title: "Construct and Rebalance a Model-Based Portfolio",
        scoring_dimensions: [
          { label: "Mandate fit", weight: 30, descriptor: "Final allocation respects ATR and restrictions" },
          { label: "Drift correction", weight: 30, descriptor: "Trades return weights within tolerance" },
          { label: "Tax sensitivity", weight: 20, descriptor: "Avoids unnecessary CGT events" },
          { label: "Rationale quality", weight: 20, descriptor: "Trade rationale is defensible" },
        ],
        topic_outline: [
          { topic: "Mandate translation", sub_points: ["Restrictions", "Legacy positions"] },
          { topic: "Trade list construction", sub_points: ["Sizing", "Sequencing"] },
        ],
        evidence_generated: ["trade_rationale_pack"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "bk4.ev_trade_rationale",
        evidence_title: "Trade Rationale Pack on Synthetic Client",
        evidence_type: "trade_rationale", reviewer_role: "assessor", submission_format: "upload",
        required_for_gate: true },
    ],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "bk5.regulatory_landscape",
    module_title: "Regulatory Landscape — FCA, COBS and Consumer Duty Essentials",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "business_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["fca_principles", "cobs_application", "consumer_duty_application"],
    estimated_effort_hours: 5, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "digital",
    nudge_trigger_tags: ["consumer_duty_review", "fca_thematic_review"],
    stretch_unlock_conditions: [], risk_flags_if_not_completed: ["regulatory_breach_risk"],
    display_order: 50,
    chapters: [
      { chapter_code: "bk5.c1", chapter_title: "FCA Principles for Businesses in Practice",
        learning_objective: "Explain the FCA principles most relevant to discretionary wealth.",
        content_type: "reading", estimated_time_minutes: 30, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["fca_principles"],
        related_capabilities: ["fca_principles"], complexity: 1.5 },
      { chapter_code: "bk5.c2", chapter_title: "COBS Highlights for Investment Staff",
        learning_objective: "Apply key COBS rules around suitability, communications and conflicts.",
        content_type: "case_study", estimated_time_minutes: 35, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["cobs"],
        related_capabilities: ["cobs_application"], complexity: 1.8 },
      { chapter_code: "bk5.c3", chapter_title: "Consumer Duty in Daily Practice",
        learning_objective: "Identify Consumer Duty obligations across the four outcomes for IM activity.",
        content_type: "scenario_walkthrough", estimated_time_minutes: 30, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["consumer_duty"],
        related_capabilities: ["consumer_duty_application"], complexity: 1.9 },
    ],
    blueprints: [
      { blueprint_code: "bk5.bp_post", scope: "module_post",
        assessment_type: "compliance_review_task",
        assessment_title: "Spot the Regulatory Breach",
        scoring_dimensions: [
          { label: "Issue identification", weight: 40, descriptor: "Flags all material breaches" },
          { label: "Rule citation", weight: 30, descriptor: "Names correct rule families" },
          { label: "Remediation logic", weight: 30, descriptor: "Proposes proportionate fixes" },
        ],
        topic_outline: [
          { topic: "Suitability breach indicators", sub_points: [] },
          { topic: "Communication failures", sub_points: [] },
        ],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
];

// ───────────────────────── Technical Knowledge (7) ─────────────────────────
const technicalKnowledge: ModuleSkeleton[] = [
  {
    module_code: "tk1.charles_river_ims",
    module_title: "Charles River IMS — Order, Trade and Compliance Workflows",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "technical_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["charles_river_navigation", "order_workflow_execution", "pre_trade_compliance"],
    estimated_effort_hours: 6, difficulty_level: "practitioner",
    prerequisite_module_codes: ["bk4.portfolio_construction"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "simulation",
    nudge_trigger_tags: ["pre_first_trade", "compliance_alert_review"],
    stretch_unlock_conditions: [], risk_flags_if_not_completed: ["trade_error_risk", "compliance_breach_risk"],
    display_order: 110,
    chapters: [
      { chapter_code: "tk1.c1", chapter_title: "Charles River Navigation and Key Screens",
        learning_objective: "Navigate Charles River screens for portfolios, orders and compliance.",
        content_type: "system_practice", estimated_time_minutes: 40, difficulty_level: "practitioner",
        delivery_mode: "simulation", topic_tags: ["charles_river", "navigation"],
        related_capabilities: ["charles_river_navigation"], complexity: 2.2 },
      { chapter_code: "tk1.c2", chapter_title: "Building and Submitting an Order Block",
        learning_objective: "Construct an order block with correct sizing, account, and venue selection.",
        content_type: "system_practice", estimated_time_minutes: 50, difficulty_level: "practitioner",
        delivery_mode: "simulation", topic_tags: ["order_block", "execution"],
        related_capabilities: ["order_workflow_execution"], complexity: 2.6 },
      { chapter_code: "tk1.c3", chapter_title: "Pre-Trade Compliance Checks and Alerts",
        learning_objective: "Interpret compliance alerts and resolve them within policy.",
        content_type: "scenario_walkthrough", estimated_time_minutes: 35, difficulty_level: "practitioner",
        delivery_mode: "simulation", topic_tags: ["pre_trade_compliance", "alerts"],
        related_capabilities: ["pre_trade_compliance"], complexity: 2.5 },
    ],
    blueprints: [
      { blueprint_code: "tk1.bp_post", scope: "module_post",
        assessment_type: "system_task_simulation",
        assessment_title: "End-to-End Trade Execution in Charles River",
        scoring_dimensions: [
          { label: "Workflow correctness", weight: 40, descriptor: "All steps in correct order" },
          { label: "Compliance handling", weight: 30, descriptor: "Alerts resolved correctly" },
          { label: "Audit trail quality", weight: 30, descriptor: "Notes and rationale captured" },
        ],
        topic_outline: [
          { topic: "Order construction", sub_points: ["Account", "Venue", "Size"] },
          { topic: "Compliance alert resolution", sub_points: [] },
        ],
        evidence_generated: ["system_task_recording"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "tk1.ev_system_pack",
        evidence_title: "Charles River Workflow Screenshot Pack",
        evidence_type: "system_screenshot_pack", reviewer_role: "manager",
        submission_format: "system_record", required_for_gate: true },
    ],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "tk2.bloomberg_essentials",
    module_title: "Bloomberg Terminal Essentials for IMs",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "technical_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["bloomberg_navigation", "security_research_workflow", "watchlist_management"],
    estimated_effort_hours: 4, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["pre_research_task"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["research_quality_gap"],
    display_order: 120,
    chapters: [
      { chapter_code: "tk2.c1", chapter_title: "Navigation, Tickers and Functions",
        learning_objective: "Use core Bloomberg functions (DES, GP, FA, RV) confidently.",
        content_type: "video", estimated_time_minutes: 25, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["bloomberg", "functions"],
        related_capabilities: ["bloomberg_navigation"], complexity: 1.8 },
      { chapter_code: "tk2.c2", chapter_title: "Researching a Single Security End-to-End",
        learning_objective: "Build a one-page research note from Bloomberg data on one security.",
        content_type: "workplace_assignment", estimated_time_minutes: 45, difficulty_level: "practitioner",
        delivery_mode: "workplace_practice", topic_tags: ["security_research"],
        related_capabilities: ["security_research_workflow"], complexity: 2.3 },
    ],
    blueprints: [
      { blueprint_code: "tk2.bp_post", scope: "module_post",
        assessment_type: "system_task_simulation",
        assessment_title: "Bloomberg Research Task",
        scoring_dimensions: [
          { label: "Function selection", weight: 40, descriptor: "Uses appropriate functions" },
          { label: "Data interpretation", weight: 40, descriptor: "Reads charts and ratios correctly" },
          { label: "Output quality", weight: 20, descriptor: "Concise, structured note" },
        ],
        topic_outline: [
          { topic: "Function workflow", sub_points: [] },
          { topic: "Note structure", sub_points: [] },
        ],
        evidence_generated: ["research_one_pager"] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "tk3.performance_attribution",
    module_title: "Performance Measurement, Attribution and Benchmarking",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "technical_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["performance_measurement", "attribution_analysis", "benchmark_selection"],
    estimated_effort_hours: 5, difficulty_level: "practitioner",
    prerequisite_module_codes: ["bk4.portfolio_construction"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["pre_quarterly_review"],
    stretch_unlock_conditions: [], risk_flags_if_not_completed: ["client_review_credibility_gap"],
    display_order: 130,
    chapters: [
      { chapter_code: "tk3.c1", chapter_title: "TWR vs MWR and Why It Matters",
        learning_objective: "Compute and interpret time- and money-weighted returns.",
        content_type: "reading", estimated_time_minutes: 30, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["twr", "mwr"],
        related_capabilities: ["performance_measurement"], complexity: 2.2 },
      { chapter_code: "tk3.c2", chapter_title: "Brinson Attribution Walkthrough",
        learning_objective: "Decompose excess return into allocation and selection effects.",
        content_type: "scenario_walkthrough", estimated_time_minutes: 35, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["attribution", "brinson"],
        related_capabilities: ["attribution_analysis"], complexity: 2.6 },
      { chapter_code: "tk3.c3", chapter_title: "Choosing and Defending a Benchmark",
        learning_objective: "Select an appropriate benchmark for a client mandate and defend the choice.",
        content_type: "case_study", estimated_time_minutes: 30, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["benchmark"],
        related_capabilities: ["benchmark_selection"], complexity: 2.3 },
    ],
    blueprints: [
      { blueprint_code: "tk3.bp_post", scope: "module_post",
        assessment_type: "calculation_exercise",
        assessment_title: "Performance and Attribution Calculation Set",
        scoring_dimensions: [
          { label: "Calculation accuracy", weight: 50, descriptor: "Correct TWR, MWR, attribution" },
          { label: "Interpretation", weight: 30, descriptor: "Explains drivers in plain English" },
          { label: "Benchmark rationale", weight: 20, descriptor: "Defends benchmark choice" },
        ],
        topic_outline: [
          { topic: "Return calculations", sub_points: ["TWR", "MWR"] },
          { topic: "Attribution", sub_points: ["Allocation", "Selection"] },
        ],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "tk4.risk_mandate_restrictions",
    module_title: "Risk Profiling, Mandate Mapping and Investment Restrictions",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "technical_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["risk_profiling", "mandate_mapping", "restriction_handling"],
    estimated_effort_hours: 5, difficulty_level: "practitioner",
    prerequisite_module_codes: ["bk2.kyc_suitability"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["new_client_onboarding"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["mandate_breach_risk"],
    display_order: 140,
    chapters: [
      { chapter_code: "tk4.c1", chapter_title: "From ATR Score to Mandate Selection",
        learning_objective: "Translate a risk score and CFL into a mandate band.",
        content_type: "reading", estimated_time_minutes: 25, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["risk_profiling", "mandate"],
        related_capabilities: ["risk_profiling"], complexity: 2.0 },
      { chapter_code: "tk4.c2", chapter_title: "Handling Client Restrictions and ESG Exclusions",
        learning_objective: "Implement bespoke restrictions and reflect them in Charles River.",
        content_type: "system_practice", estimated_time_minutes: 40, difficulty_level: "practitioner",
        delivery_mode: "simulation", topic_tags: ["restrictions", "esg_exclusions"],
        related_capabilities: ["restriction_handling"], complexity: 2.5 },
    ],
    blueprints: [
      { blueprint_code: "tk4.bp_post", scope: "module_post",
        assessment_type: "case_analysis",
        assessment_title: "Mandate Mapping Case",
        scoring_dimensions: [
          { label: "Mandate fit", weight: 40, descriptor: "Correct band selected" },
          { label: "Restriction implementation", weight: 40, descriptor: "Restrictions captured correctly" },
          { label: "Documentation", weight: 20, descriptor: "Audit trail clear" },
        ],
        topic_outline: [
          { topic: "Risk band selection", sub_points: [] },
          { topic: "Restriction encoding", sub_points: [] },
        ],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "tk5.tax_wrappers",
    module_title: "Tax-Efficient Wrappers — ISA, SIPP, GIA and Trusts",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "technical_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["wrapper_selection", "tax_efficient_planning", "wrapper_admin_awareness"],
    estimated_effort_hours: 5, difficulty_level: "practitioner",
    prerequisite_module_codes: ["bk2.kyc_suitability"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["tax_year_end", "isa_subscription_window"],
    stretch_unlock_conditions: [], risk_flags_if_not_completed: ["tax_inefficiency_risk"],
    display_order: 150,
    chapters: [
      { chapter_code: "tk5.c1", chapter_title: "Wrapper Map — When to Use Which",
        learning_objective: "Choose between ISA, SIPP, GIA and Trust based on client circumstances.",
        content_type: "reading", estimated_time_minutes: 30, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["wrappers", "isa", "sipp"],
        related_capabilities: ["wrapper_selection"], complexity: 2.0 },
      { chapter_code: "tk5.c2", chapter_title: "Tax-Efficient Withdrawal Sequencing",
        learning_objective: "Sequence withdrawals across wrappers to minimise tax drag.",
        content_type: "case_study", estimated_time_minutes: 35, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["withdrawals", "tax_drag"],
        related_capabilities: ["tax_efficient_planning"], complexity: 2.4 },
    ],
    blueprints: [
      { blueprint_code: "tk5.bp_post", scope: "module_post",
        assessment_type: "scenario_response",
        assessment_title: "Wrapper Recommendation Scenario",
        scoring_dimensions: [
          { label: "Wrapper choice fit", weight: 50, descriptor: "Recommends optimal wrappers" },
          { label: "Tax logic", weight: 30, descriptor: "Articulates tax rationale" },
          { label: "Client framing", weight: 20, descriptor: "Explains in plain language" },
        ],
        topic_outline: [
          { topic: "Wrapper attributes", sub_points: [] },
          { topic: "Sequencing logic", sub_points: [] },
        ],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "tk6.esg_responsible_investing",
    module_title: "ESG Integration and Responsible Investing at Rathbones",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "technical_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["esg_integration", "responsible_investing_dialogue", "exclusion_management"],
    estimated_effort_hours: 4, difficulty_level: "practitioner",
    prerequisite_module_codes: ["bk1.intro_wealth_rathbones"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["client_esg_question"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["esg_credibility_gap"],
    display_order: 160,
    chapters: [
      { chapter_code: "tk6.c1", chapter_title: "Rathbones' Approach to Responsible Investing",
        learning_objective: "Articulate the firm's ESG integration approach and stewardship model.",
        content_type: "reading", estimated_time_minutes: 30, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["esg", "stewardship"],
        related_capabilities: ["esg_integration"], complexity: 2.0 },
      { chapter_code: "tk6.c2", chapter_title: "Handling Client Conversations on ESG",
        learning_objective: "Lead a conversation about ESG preferences and translate them into mandate restrictions.",
        content_type: "role_play_assessed", estimated_time_minutes: 35, difficulty_level: "practitioner",
        delivery_mode: "simulation", topic_tags: ["client_dialogue", "esg"],
        related_capabilities: ["responsible_investing_dialogue"], complexity: 2.4 },
    ],
    blueprints: [
      { blueprint_code: "tk6.bp_post", scope: "module_post",
        assessment_type: "client_simulation_chat",
        assessment_title: "ESG Preferences Client Conversation",
        scoring_dimensions: [
          { label: "Question quality", weight: 30, descriptor: "Probes preferences without leading" },
          { label: "Translation to mandate", weight: 40, descriptor: "Maps preferences to restrictions" },
          { label: "Avoidance of greenwashing", weight: 30, descriptor: "Stays factually accurate" },
        ],
        topic_outline: [
          { topic: "Preference probing", sub_points: [] },
          { topic: "Mandate translation", sub_points: [] },
        ],
        evidence_generated: ["client_dialogue_transcript"] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "tk7.ops_workflows",
    module_title: "Operational Workflows — Settlements, Corporate Actions, Reconciliations",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "technical_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["settlement_understanding", "corporate_actions_handling", "reconciliation_basics"],
    estimated_effort_hours: 4, difficulty_level: "foundation",
    prerequisite_module_codes: ["tk1.charles_river_ims"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["corporate_action_event"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["operational_error_risk"],
    display_order: 170,
    chapters: [
      { chapter_code: "tk7.c1", chapter_title: "Settlement Cycles and Failed Trades",
        learning_objective: "Explain T+ cycles and what to do when a trade fails.",
        content_type: "reading", estimated_time_minutes: 25, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["settlement"],
        related_capabilities: ["settlement_understanding"], complexity: 1.6 },
      { chapter_code: "tk7.c2", chapter_title: "Corporate Actions in a Discretionary Book",
        learning_objective: "Handle voluntary and mandatory corporate actions correctly.",
        content_type: "scenario_walkthrough", estimated_time_minutes: 30, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["corporate_actions"],
        related_capabilities: ["corporate_actions_handling"], complexity: 1.8 },
    ],
    blueprints: [
      { blueprint_code: "tk7.bp_post", scope: "module_post",
        assessment_type: "knowledge_check_mcq",
        assessment_title: "Operations Knowledge Check",
        scoring_dimensions: [
          { label: "Definitions", weight: 50, descriptor: "Correctly identifies operational terms" },
          { label: "Action selection", weight: 50, descriptor: "Picks correct response in scenario" },
        ],
        topic_outline: [
          { topic: "Settlement issues", sub_points: [] },
          { topic: "Corporate action types", sub_points: [] },
        ],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
];

// ───────────────────────── Behavioural Skills (5) ─────────────────────────
const behavioural: ModuleSkeleton[] = [
  {
    module_code: "bs1.client_communication",
    module_title: "Client Communication and Active Listening",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "behavioural_skills",
    progression_stage: STAGE,
    target_capabilities: ["active_listening", "client_rapport_building", "concise_explanation"],
    estimated_effort_hours: 4, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "live_cohort",
    nudge_trigger_tags: ["pre_first_client_call"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["client_relationship_risk"],
    display_order: 210,
    chapters: [
      { chapter_code: "bs1.c1", chapter_title: "Active Listening Frameworks",
        learning_objective: "Apply active listening techniques in client conversations.",
        content_type: "video", estimated_time_minutes: 25, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["active_listening"],
        related_capabilities: ["active_listening"], complexity: 1.6 },
      { chapter_code: "bs1.c2", chapter_title: "Practice — Discovery Conversation",
        learning_objective: "Lead a 10-minute discovery conversation with a synthetic client.",
        content_type: "role_play_assessed", estimated_time_minutes: 30, difficulty_level: "practitioner",
        delivery_mode: "simulation", topic_tags: ["discovery_call"],
        related_capabilities: ["client_rapport_building"], complexity: 2.2 },
    ],
    blueprints: [
      { blueprint_code: "bs1.bp_post", scope: "module_post",
        assessment_type: "client_simulation_voice",
        assessment_title: "Discovery Call Simulation",
        scoring_dimensions: [
          { label: "Open questioning", weight: 30, descriptor: "Uses open, exploratory questions" },
          { label: "Reflection and summary", weight: 30, descriptor: "Reflects back accurately" },
          { label: "Empathy signals", weight: 20, descriptor: "Demonstrates warmth" },
          { label: "Time control", weight: 20, descriptor: "Keeps conversation on track" },
        ],
        topic_outline: [
          { topic: "Discovery flow", sub_points: [] },
          { topic: "Listening techniques", sub_points: [] },
        ],
        evidence_generated: ["voice_simulation_recording"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "bs1.ev_observation",
        evidence_title: "Manager Observation — First Live Client Call",
        evidence_type: "manager_observation_form", reviewer_role: "manager",
        submission_format: "observation", required_for_gate: true },
    ],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "bs2.difficult_conversations",
    module_title: "Difficult Conversations and Managing Volatility Updates",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "behavioural_skills",
    progression_stage: STAGE,
    target_capabilities: ["difficult_conversation_handling", "volatility_communication", "expectation_management"],
    estimated_effort_hours: 4, difficulty_level: "practitioner",
    prerequisite_module_codes: ["bs1.client_communication"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "live_cohort",
    nudge_trigger_tags: ["market_drawdown", "client_complaint_signal"],
    stretch_unlock_conditions: [], risk_flags_if_not_completed: ["client_attrition_risk"],
    display_order: 220,
    chapters: [
      { chapter_code: "bs2.c1", chapter_title: "Frameworks for Difficult Client Calls",
        learning_objective: "Apply a structured approach to delivering hard messages.",
        content_type: "reading", estimated_time_minutes: 25, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["difficult_conversations"],
        related_capabilities: ["difficult_conversation_handling"], complexity: 2.0 },
      { chapter_code: "bs2.c2", chapter_title: "Volatility Update — Live Practice",
        learning_objective: "Deliver a volatility update to an anxious client and manage objections.",
        content_type: "role_play_assessed", estimated_time_minutes: 35, difficulty_level: "practitioner",
        delivery_mode: "simulation", topic_tags: ["volatility_update"],
        related_capabilities: ["volatility_communication"], complexity: 2.6 },
    ],
    blueprints: [
      { blueprint_code: "bs2.bp_post", scope: "module_post",
        assessment_type: "client_simulation_voice",
        assessment_title: "Volatility Update Simulation",
        scoring_dimensions: [
          { label: "Message clarity", weight: 30, descriptor: "Delivers facts cleanly" },
          { label: "Empathy and pacing", weight: 30, descriptor: "Acknowledges feelings" },
          { label: "Action framing", weight: 20, descriptor: "Closes with clear next steps" },
          { label: "Compliance discipline", weight: 20, descriptor: "Avoids reassurance promises" },
        ],
        topic_outline: [
          { topic: "Bad news structure", sub_points: [] },
          { topic: "Handling objections", sub_points: [] },
        ],
        evidence_generated: ["voice_simulation_recording"] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "bs3.delegation_stakeholders",
    module_title: "Delegation, Stakeholder Management and Working with IMs",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "behavioural_skills",
    progression_stage: STAGE,
    target_capabilities: ["task_handover", "im_collaboration", "internal_stakeholder_management"],
    estimated_effort_hours: 3, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["new_team_assignment"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["coordination_failure_risk"],
    display_order: 230,
    chapters: [
      { chapter_code: "bs3.c1", chapter_title: "Working Effectively with Your IM",
        learning_objective: "Set expectations and feedback loops with the supervising IM.",
        content_type: "mentor_discussion", estimated_time_minutes: 30, difficulty_level: "foundation",
        delivery_mode: "coaching", topic_tags: ["im_collaboration"],
        related_capabilities: ["im_collaboration"], complexity: 1.8 },
      { chapter_code: "bs3.c2", chapter_title: "Handover and Escalation Patterns",
        learning_objective: "Use handover and escalation patterns to keep work safe.",
        content_type: "reading", estimated_time_minutes: 20, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["handover", "escalation"],
        related_capabilities: ["task_handover"], complexity: 1.6 },
    ],
    blueprints: [
      { blueprint_code: "bs3.bp_post", scope: "module_post",
        assessment_type: "reflective_journal",
        assessment_title: "Delegation Reflection",
        scoring_dimensions: [
          { label: "Specificity", weight: 50, descriptor: "Concrete examples cited" },
          { label: "Insight", weight: 50, descriptor: "Identifies what to change" },
        ],
        topic_outline: [
          { topic: "Working with IM", sub_points: [] },
          { topic: "Escalation choices", sub_points: [] },
        ],
        evidence_generated: ["reflection_writeup"] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "bs4.judgement_ethics",
    module_title: "Professional Judgement and Ethical Decision-Making",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "behavioural_skills",
    progression_stage: STAGE,
    target_capabilities: ["ethical_judgement", "conflicts_of_interest_handling", "speak_up_culture"],
    estimated_effort_hours: 3, difficulty_level: "practitioner",
    prerequisite_module_codes: ["bk5.regulatory_landscape"], is_core_required: true,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["ethics_dilemma_signal"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["conduct_breach_risk"],
    display_order: 240,
    chapters: [
      { chapter_code: "bs4.c1", chapter_title: "Spotting Ethical Dilemmas",
        learning_objective: "Recognise common ethical traps in IM work.",
        content_type: "case_study", estimated_time_minutes: 30, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["ethics"],
        related_capabilities: ["ethical_judgement"], complexity: 2.0 },
      { chapter_code: "bs4.c2", chapter_title: "Speaking Up and Escalating Concerns",
        learning_objective: "Use the firm's escalation channels with confidence.",
        content_type: "scenario_walkthrough", estimated_time_minutes: 25, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["speak_up", "escalation"],
        related_capabilities: ["speak_up_culture"], complexity: 2.0 },
    ],
    blueprints: [
      { blueprint_code: "bs4.bp_post", scope: "module_post",
        assessment_type: "scenario_response",
        assessment_title: "Ethical Dilemma Response",
        scoring_dimensions: [
          { label: "Issue framing", weight: 40, descriptor: "Names the conflict precisely" },
          { label: "Action choice", weight: 40, descriptor: "Selects defensible action" },
          { label: "Documentation discipline", weight: 20, descriptor: "Captures rationale" },
        ],
        topic_outline: [
          { topic: "Conflict identification", sub_points: [] },
          { topic: "Action and escalation", sub_points: [] },
        ],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "bs5.time_prioritisation",
    module_title: "Time Management and Prioritisation in a Client Book",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "behavioural_skills",
    progression_stage: STAGE,
    target_capabilities: ["prioritisation", "client_book_planning", "personal_workflow"],
    estimated_effort_hours: 3, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["workload_spike"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["sla_miss_risk"],
    display_order: 250,
    chapters: [
      { chapter_code: "bs5.c1", chapter_title: "Prioritising Across a Client Book",
        learning_objective: "Sequence work across a client book using risk and value.",
        content_type: "reading", estimated_time_minutes: 25, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["prioritisation"],
        related_capabilities: ["prioritisation"], complexity: 1.6 },
      { chapter_code: "bs5.c2", chapter_title: "Building a Weekly Plan",
        learning_objective: "Build and defend a realistic weekly plan with mentor.",
        content_type: "coaching", estimated_time_minutes: 30, difficulty_level: "foundation",
        delivery_mode: "coaching", topic_tags: ["weekly_plan"],
        related_capabilities: ["client_book_planning"], complexity: 1.8 },
    ],
    blueprints: [
      { blueprint_code: "bs5.bp_post", scope: "module_post",
        assessment_type: "reflective_journal",
        assessment_title: "Weekly Planning Reflection",
        scoring_dimensions: [
          { label: "Realism", weight: 50, descriptor: "Plan is achievable" },
          { label: "Reasoning", weight: 50, descriptor: "Justifies prioritisation" },
        ],
        topic_outline: [{ topic: "Plan critique", sub_points: [] }],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
];

// ──────────── Certification & Professional Standards (5) ────────────
const certification: ModuleSkeleton[] = [
  {
    module_code: "cps1.cisi_ioc_securities",
    module_title: "CISI IOC — Securities Foundations (Study Path)",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "certification_professional_standards",
    progression_stage: STAGE,
    target_capabilities: ["cisi_ioc_securities_readiness"],
    estimated_effort_hours: 30, difficulty_level: "practitioner",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "self_study" as any,
    nudge_trigger_tags: ["cisi_exam_window"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["regulatory_qualification_gap"],
    display_order: 310,
    chapters: [
      { chapter_code: "cps1.c1", chapter_title: "CISI IOC Study Plan and Milestones",
        learning_objective: "Build and commit to a 12-week CISI study plan.",
        content_type: "self_study", estimated_time_minutes: 40, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["cisi", "study_plan"],
        related_capabilities: ["cisi_ioc_securities_readiness"], complexity: 1.8 },
      { chapter_code: "cps1.c2", chapter_title: "Topic Coverage Tracker — IOC Securities",
        learning_objective: "Track CISI topic coverage and self-test results.",
        content_type: "workplace_assignment", estimated_time_minutes: 60, difficulty_level: "practitioner",
        delivery_mode: "workplace_practice", topic_tags: ["cisi_tracker"],
        related_capabilities: ["cisi_ioc_securities_readiness"], complexity: 2.0 },
    ],
    blueprints: [
      { blueprint_code: "cps1.bp_post", scope: "module_post",
        assessment_type: "external_certification",
        assessment_title: "CISI IOC Securities Result",
        scoring_dimensions: [
          { label: "Pass status", weight: 100, descriptor: "Pass / fail per CISI" },
        ],
        topic_outline: [{ topic: "CISI exam", sub_points: ["Booked", "Sat", "Result"] }],
        evidence_generated: ["external_certificate"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "cps1.ev_certificate",
        evidence_title: "CISI IOC Certificate Upload",
        evidence_type: "case_writeup", reviewer_role: "manager",
        submission_format: "upload", required_for_gate: true },
    ],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "cps2.cisi_iad_bridge",
    module_title: "CISI Investment Advice Diploma — Bridging Module",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "certification_professional_standards",
    progression_stage: STAGE,
    target_capabilities: ["cisi_iad_readiness"],
    estimated_effort_hours: 12, difficulty_level: "practitioner",
    prerequisite_module_codes: ["cps1.cisi_ioc_securities"], is_core_required: false,
    is_stretch_module: false, stretch_target_role_cohort: null,
    recommended_delivery_mode: "self_study" as any,
    nudge_trigger_tags: ["iad_planning_window"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: [],
    display_order: 320,
    chapters: [
      { chapter_code: "cps2.c1", chapter_title: "From IOC to IAD — Gap Map",
        learning_objective: "Identify the gap between IOC and IAD and plan study.",
        content_type: "self_study", estimated_time_minutes: 40, difficulty_level: "practitioner",
        delivery_mode: "digital", topic_tags: ["iad", "gap_map"],
        related_capabilities: ["cisi_iad_readiness"], complexity: 2.0 },
    ],
    blueprints: [
      { blueprint_code: "cps2.bp_post", scope: "module_post",
        assessment_type: "reflective_journal",
        assessment_title: "IAD Study Commitment",
        scoring_dimensions: [{ label: "Plan completeness", weight: 100, descriptor: "Plan is realistic" }],
        topic_outline: [{ topic: "IAD plan", sub_points: [] }],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [],
  },
  {
    module_code: "cps3.smcr_conduct",
    module_title: "SMCR and Conduct Rules for Investment Staff",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "certification_professional_standards",
    progression_stage: STAGE,
    target_capabilities: ["smcr_application", "conduct_rules_application"],
    estimated_effort_hours: 3, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "digital",
    nudge_trigger_tags: ["annual_attestation"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["conduct_breach_risk"],
    display_order: 330,
    chapters: [
      { chapter_code: "cps3.c1", chapter_title: "Conduct Rules in Daily Practice",
        learning_objective: "Apply each Conduct Rule to common IM scenarios.",
        content_type: "scenario_walkthrough", estimated_time_minutes: 30, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["smcr", "conduct_rules"],
        related_capabilities: ["conduct_rules_application"], complexity: 1.8 },
    ],
    blueprints: [
      { blueprint_code: "cps3.bp_post", scope: "module_post",
        assessment_type: "knowledge_check_mcq",
        assessment_title: "Conduct Rules Knowledge Check",
        scoring_dimensions: [{ label: "Accuracy", weight: 100, descriptor: "Correct identifications" }],
        topic_outline: [{ topic: "Conduct rule application", sub_points: [] }],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "cps4.aml_financial_crime",
    module_title: "Anti-Money Laundering and Financial Crime Prevention",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "certification_professional_standards",
    progression_stage: STAGE,
    target_capabilities: ["aml_red_flag_detection", "sar_process_understanding"],
    estimated_effort_hours: 3, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "digital",
    nudge_trigger_tags: ["aml_alert"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["aml_breach_risk"],
    display_order: 340,
    chapters: [
      { chapter_code: "cps4.c1", chapter_title: "Spotting Red Flags",
        learning_objective: "Identify common AML and fraud red flags in IM workflows.",
        content_type: "case_study", estimated_time_minutes: 30, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["aml", "red_flags"],
        related_capabilities: ["aml_red_flag_detection"], complexity: 1.8 },
    ],
    blueprints: [
      { blueprint_code: "cps4.bp_post", scope: "module_post",
        assessment_type: "scenario_response",
        assessment_title: "Red Flag Triage Scenario",
        scoring_dimensions: [
          { label: "Red flag identification", weight: 50, descriptor: "Spots all flags" },
          { label: "Escalation path", weight: 50, descriptor: "Triggers SAR process" },
        ],
        topic_outline: [{ topic: "Red flag triage", sub_points: [] }],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
  {
    module_code: "cps5.cpd_plan",
    module_title: "Continuing Professional Development Plan",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "certification_professional_standards",
    progression_stage: STAGE,
    target_capabilities: ["cpd_planning"],
    estimated_effort_hours: 2, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "digital",
    nudge_trigger_tags: ["cpd_year_end"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["cpd_shortfall_risk"],
    display_order: 350,
    chapters: [
      { chapter_code: "cps5.c1", chapter_title: "Building a 12-Month CPD Plan",
        learning_objective: "Author a CPD plan that meets CISI hour requirements.",
        content_type: "workplace_assignment", estimated_time_minutes: 40, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["cpd"],
        related_capabilities: ["cpd_planning"], complexity: 1.5 },
    ],
    blueprints: [
      { blueprint_code: "cps5.bp_post", scope: "module_post",
        assessment_type: "reflective_journal",
        assessment_title: "CPD Plan Submission",
        scoring_dimensions: [{ label: "Plan completeness", weight: 100, descriptor: "Hours and topics covered" }],
        topic_outline: [{ topic: "CPD plan", sub_points: [] }],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [GATE],
  },
];

// ──────────────────────── Other Enablers (4) ────────────────────────
const enablers: ModuleSkeleton[] = [
  {
    module_code: "oe1.systems_tour",
    module_title: "Internal Systems Stack Tour (Rathbones-Specific)",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "other_enablers",
    progression_stage: STAGE,
    target_capabilities: ["systems_navigation"],
    estimated_effort_hours: 3, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["onboarding_week_1"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["productivity_blocker"],
    display_order: 410,
    chapters: [
      { chapter_code: "oe1.c1", chapter_title: "End-to-End Systems Tour",
        learning_objective: "Navigate Rathbones' core internal systems.",
        content_type: "video", estimated_time_minutes: 30, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["systems"],
        related_capabilities: ["systems_navigation"], complexity: 1.4 },
    ],
    blueprints: [
      { blueprint_code: "oe1.bp_post", scope: "module_post",
        assessment_type: "knowledge_check_mcq",
        assessment_title: "Systems Stack Quick Check",
        scoring_dimensions: [{ label: "Identification", weight: 100, descriptor: "Names systems and their use" }],
        topic_outline: [{ topic: "Systems map", sub_points: [] }],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [],
  },
  {
    module_code: "oe2.mentor_buddy",
    module_title: "Mentor and Buddy System Onboarding",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "other_enablers",
    progression_stage: STAGE,
    target_capabilities: ["mentor_relationship_setup"],
    estimated_effort_hours: 2, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "coaching",
    nudge_trigger_tags: ["onboarding_week_1"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["isolation_risk"],
    display_order: 420,
    chapters: [
      { chapter_code: "oe2.c1", chapter_title: "First Mentor Conversation",
        learning_objective: "Run a productive first mentor conversation and set goals.",
        content_type: "mentor_discussion", estimated_time_minutes: 45, difficulty_level: "foundation",
        delivery_mode: "coaching", topic_tags: ["mentor"],
        related_capabilities: ["mentor_relationship_setup"], complexity: 1.5 },
    ],
    blueprints: [
      { blueprint_code: "oe2.bp_post", scope: "module_post",
        assessment_type: "mentor_signoff",
        assessment_title: "Mentor Confirms Setup",
        scoring_dimensions: [{ label: "Mentor signoff", weight: 100, descriptor: "Mentor confirms goals set" }],
        topic_outline: [{ topic: "Mentor first session", sub_points: [] }],
        evidence_generated: ["mentor_form"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "oe2.ev_mentor_form",
        evidence_title: "Mentor Sign-Off Form",
        evidence_type: "mentor_feedback_form", reviewer_role: "mentor",
        submission_format: "written", required_for_gate: false },
    ],
    contributes_to_gates: [],
  },
  {
    module_code: "oe3.reflective_practice",
    module_title: "Reflective Practice and Learning Journal Habits",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "other_enablers",
    progression_stage: STAGE,
    target_capabilities: ["reflective_practice"],
    estimated_effort_hours: 2, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "digital",
    nudge_trigger_tags: ["weekly_reflection_window"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["growth_velocity_risk"],
    display_order: 430,
    chapters: [
      { chapter_code: "oe3.c1", chapter_title: "Reflection Frameworks That Work",
        learning_objective: "Use a structured reflection model weekly.",
        content_type: "reading", estimated_time_minutes: 20, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["reflection"],
        related_capabilities: ["reflective_practice"], complexity: 1.4 },
    ],
    blueprints: [
      { blueprint_code: "oe3.bp_post", scope: "module_post",
        assessment_type: "reflective_journal",
        assessment_title: "First Reflection Submission",
        scoring_dimensions: [{ label: "Depth", weight: 100, descriptor: "Specific and honest" }],
        topic_outline: [{ topic: "Reflection prompt", sub_points: [] }],
        evidence_generated: [] },
    ],
    evidence_tasks: [],
    contributes_to_gates: [],
  },
  {
    module_code: "oe4.working_with_planners",
    module_title: "Working with Wealth Planners and Multi-Disciplinary Teams",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "other_enablers",
    progression_stage: STAGE,
    target_capabilities: ["mdt_collaboration"],
    estimated_effort_hours: 3, difficulty_level: "foundation",
    prerequisite_module_codes: [], is_core_required: true, is_stretch_module: false,
    stretch_target_role_cohort: null, recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["joint_client_meeting"], stretch_unlock_conditions: [],
    risk_flags_if_not_completed: ["client_handover_risk"],
    display_order: 440,
    chapters: [
      { chapter_code: "oe4.c1", chapter_title: "Roles, Boundaries and Handovers",
        learning_objective: "Map roles between IM and Wealth Planning teams.",
        content_type: "reading", estimated_time_minutes: 25, difficulty_level: "foundation",
        delivery_mode: "digital", topic_tags: ["mdt", "handover"],
        related_capabilities: ["mdt_collaboration"], complexity: 1.6 },
      { chapter_code: "oe4.c2", chapter_title: "Joint Client Meeting Practice",
        learning_objective: "Co-lead a joint client meeting with a Wealth Planner.",
        content_type: "observed_practice", estimated_time_minutes: 45, difficulty_level: "practitioner",
        delivery_mode: "workplace_practice", topic_tags: ["joint_meeting"],
        related_capabilities: ["mdt_collaboration"], complexity: 2.2 },
    ],
    blueprints: [
      { blueprint_code: "oe4.bp_post", scope: "module_post",
        assessment_type: "manager_observation",
        assessment_title: "Joint Meeting Observation",
        scoring_dimensions: [
          { label: "Role clarity", weight: 50, descriptor: "Clean handover and lanes" },
          { label: "Client experience", weight: 50, descriptor: "Coherent for the client" },
        ],
        topic_outline: [{ topic: "Joint meeting flow", sub_points: [] }],
        evidence_generated: ["manager_observation_form"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "oe4.ev_observation",
        evidence_title: "Manager Observation — Joint Meeting",
        evidence_type: "manager_observation_form", reviewer_role: "manager",
        submission_format: "observation", required_for_gate: true },
    ],
    contributes_to_gates: [GATE],
  },
];

// ─────────────────────── Stretch modules → IM ───────────────────────
const stretch: ModuleSkeleton[] = [
  {
    module_code: "str1.lead_client_review",
    module_title: "Stretch — Leading a Client Review End-to-End",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "behavioural_skills",
    progression_stage: STAGE,
    target_capabilities: ["full_client_review_ownership"],
    estimated_effort_hours: 5, difficulty_level: "advanced",
    prerequisite_module_codes: ["bs2.difficult_conversations", "tk3.performance_attribution"],
    is_core_required: false, is_stretch_module: true, stretch_target_role_cohort: "im",
    recommended_delivery_mode: "workplace_practice",
    nudge_trigger_tags: ["stretch_signal"],
    stretch_unlock_conditions: ["passed_bs2", "passed_tk3"],
    risk_flags_if_not_completed: [],
    display_order: 510,
    chapters: [
      { chapter_code: "str1.c1", chapter_title: "Owning the Full Review Cycle",
        learning_objective: "Plan, lead and follow up a complete client review.",
        content_type: "observed_practice", estimated_time_minutes: 60, difficulty_level: "advanced",
        delivery_mode: "workplace_practice", topic_tags: ["client_review_lead"],
        related_capabilities: ["full_client_review_ownership"], complexity: 2.8 },
    ],
    blueprints: [
      { blueprint_code: "str1.bp_post", scope: "module_post",
        assessment_type: "manager_observation",
        assessment_title: "Lead Client Review — Manager Observation",
        scoring_dimensions: [
          { label: "End-to-end ownership", weight: 60, descriptor: "Owned prep, meeting, follow-up" },
          { label: "Client outcome", weight: 40, descriptor: "Client felt well-served" },
        ],
        topic_outline: [{ topic: "Review cycle", sub_points: [] }],
        evidence_generated: ["manager_observation_form"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "str1.ev_observation",
        evidence_title: "Manager Observation — Lead Review",
        evidence_type: "manager_observation_form", reviewer_role: "manager",
        submission_format: "observation", required_for_gate: false },
    ],
    contributes_to_gates: [],
  },
  {
    module_code: "str2.investment_thesis",
    module_title: "Stretch — Building and Defending an Investment Thesis",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "technical_knowledge",
    progression_stage: STAGE,
    target_capabilities: ["thesis_construction", "thesis_defence"],
    estimated_effort_hours: 6, difficulty_level: "advanced",
    prerequisite_module_codes: ["tk2.bloomberg_essentials", "tk3.performance_attribution"],
    is_core_required: false, is_stretch_module: true, stretch_target_role_cohort: "im",
    recommended_delivery_mode: "blended",
    nudge_trigger_tags: ["stretch_signal"],
    stretch_unlock_conditions: ["passed_tk2", "passed_tk3"],
    risk_flags_if_not_completed: [],
    display_order: 520,
    chapters: [
      { chapter_code: "str2.c1", chapter_title: "Thesis Construction Methodology",
        learning_objective: "Construct a defensible single-stock or fund thesis.",
        content_type: "case_study", estimated_time_minutes: 45, difficulty_level: "advanced",
        delivery_mode: "digital", topic_tags: ["thesis", "research"],
        related_capabilities: ["thesis_construction"], complexity: 2.7 },
      { chapter_code: "str2.c2", chapter_title: "Defending the Thesis to Peers",
        learning_objective: "Present and defend a thesis to a peer group with challenge.",
        content_type: "presentation_assessed" as any, estimated_time_minutes: 45, difficulty_level: "advanced",
        delivery_mode: "live_cohort", topic_tags: ["thesis_defence"],
        related_capabilities: ["thesis_defence"], complexity: 2.9 },
    ],
    blueprints: [
      { blueprint_code: "str2.bp_post", scope: "module_post",
        assessment_type: "presentation_assessed",
        assessment_title: "Investment Thesis Pitch",
        scoring_dimensions: [
          { label: "Thesis quality", weight: 50, descriptor: "Original, evidenced" },
          { label: "Defence", weight: 50, descriptor: "Handles challenge well" },
        ],
        topic_outline: [{ topic: "Pitch", sub_points: [] }],
        evidence_generated: ["presentation_recording"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "str2.ev_pitch",
        evidence_title: "Recorded Investment Thesis Pitch",
        evidence_type: "presentation_deck", reviewer_role: "assessor",
        submission_format: "recording", required_for_gate: false },
    ],
    contributes_to_gates: [],
  },
  {
    module_code: "str3.mentoring_juniors",
    module_title: "Stretch — Mentoring Junior Staff and First-Line Coaching",
    domain_code: DOMAIN, role_cohort_code: ROLE, learning_track_code: "behavioural_skills",
    progression_stage: STAGE,
    target_capabilities: ["junior_mentoring", "feedback_delivery"],
    estimated_effort_hours: 3, difficulty_level: "advanced",
    prerequisite_module_codes: ["bs1.client_communication"], is_core_required: false,
    is_stretch_module: true, stretch_target_role_cohort: "im",
    recommended_delivery_mode: "coaching",
    nudge_trigger_tags: ["stretch_signal"], stretch_unlock_conditions: ["passed_bs1"],
    risk_flags_if_not_completed: [],
    display_order: 530,
    chapters: [
      { chapter_code: "str3.c1", chapter_title: "Coaching Conversations Practice",
        learning_objective: "Run a coaching conversation with a junior peer.",
        content_type: "observed_practice", estimated_time_minutes: 45, difficulty_level: "advanced",
        delivery_mode: "workplace_practice", topic_tags: ["coaching", "feedback"],
        related_capabilities: ["junior_mentoring"], complexity: 2.6 },
    ],
    blueprints: [
      { blueprint_code: "str3.bp_post", scope: "module_post",
        assessment_type: "peer_review",
        assessment_title: "Peer Coaching Feedback",
        scoring_dimensions: [{ label: "Coaching quality", weight: 100, descriptor: "Useful to the coachee" }],
        topic_outline: [{ topic: "Coaching", sub_points: [] }],
        evidence_generated: ["peer_feedback_form"] },
    ],
    evidence_tasks: [
      { evidence_task_code: "str3.ev_peer",
        evidence_title: "Peer Coaching Feedback Form",
        evidence_type: "peer_feedback", reviewer_role: "peer",
        submission_format: "written", required_for_gate: false },
    ],
    contributes_to_gates: [],
  },
];

export const SKELETON_MODULES: ModuleSkeleton[] = [
  ...businessKnowledge,
  ...technicalKnowledge,
  ...behavioural,
  ...certification,
  ...enablers,
  ...stretch,
];
